name: Basic Python Workflow

on:
  workflow_call:
    inputs:
      black-options:
        required: false
        type: string

jobs:
  call-another-reusable:
    uses: .github/workflows/black.yml@main
    with:
      options: "${{ inputs.black-options }}"
