name: Lint with Black

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          architecture: x64
          check-latest: true

      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "--line-length 88"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code with black" && git push)
