name: Lint with Black

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Act Workaround # https://github.com/nektos/act/issues/973
        if: ${{ env.ACT }}
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash && apt install -y nodejs
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64
          check-latest: true

      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "--line-length 88 --fast"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "thespacedoctor"
          git add -A
          git pull || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code with black" && git push origin HEAD:${{ github.ref_name }})
