name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install package
        run: |
          ehco "Installing package for testing..."
          python --version
          python -m pip --version
          python -m pip install --upgrade pip
          python -m pip install .
       
      - name: Run integration tests if script exists
        run: |
          if [ -f "./.github/workflows/assest/integration-tests.sh" ]; then
            echo "Integration test script found. Running tests..."
            bash ./.github/workflows/assest/integration-tests.sh -y
          else
            echo "Integration test script not found. Skipping..."
            exit 0
          fi
