name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Act Workaround # https://github.com/nektos/act/issues/973
        if: ${{ env.ACT }}
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash && apt install -y nodejs
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Installing package and dependencies
        run: |
          python --version
          python -m pip --version
          python -m pip install --upgrade pip
          python -m pip install .
       
      - name: Check for integration test script
        id: check_script
        shell: bash
        run: |
          if [ -f "./.github/workflows/assets/integration-tests.sh" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Run integration tests
        if: steps.check_script.outputs.exists == 'true'
        shell: bash
        run: |
          set -Eeuo pipefail
          bash ./.github/workflows/assets/integration-tests.sh -y
